### ISSUE TITLE
Нельзя вводить дробное значение в часы при редактировании задачи

### ISSUE THREAD

**Issue by 0ReC0** [RTUITLab/ITLab-Projects-Front#38]
![image](https://user-images.githubusercontent.com/41593670/141862340-9afa7b41-1a94-4fb5-a46b-48af51ff4ddd.png)
## Сделайте пожалуйста возможность вводить дробные значения
![image](https://user-images.githubusercontent.com/41593670/141963054-4b45729d-a704-4f20-93c7-bc8c46e8875a.png)

**Comment by CAPCHIK** [comment]
Взяв копию расчетного листа по твоему проекту, и округлив вверх все дробные значения до целых я получил увеличение стоимости проекта на 6%
Учитывая, сколько времени вы тратите на общение, согласование, ожидание друг друга и прочее - количество реально неучтенного времени совершенно спокойно нивелирует эти колебания в получасовых (или где-то даже 0.2 часа видел) задачах
Принцип, которого придерживаемся сейчас - часы это **целые** часы, если задача настолько маленькая, что на неё нужно пол часа - нужно объединить её с другой, более сложной, либо просто округлить до часа, ибо данная сумма не будет существенной в рамках всего проекта

Сегодня как раз будет собрание, сможем там этот вопрос обсудить

**Comment by CAPCHIK** [comment]
И очень важное замечания - @0ReC0
Не публикуй, пожалуйста, личную информацию сотрудников в публичных ресурсах. Как например тут - ФИО участников.
В данной информации ничего секретного, по идее, нет, но если публиковать это - кто-то может по инерции и телефоны/почты/зарплаты случайно опубликовать, что не есть хорошо

Из того, как это можно реализовывать
1. Можешь замазывать на готовом скриншоте
2. Можешь показывать на dev стенде, с рандомными но показывающими проблему данными
3. Можешь кинуть информацию в slack, и ответственный за проект уже создаст Issue

**Comment by 0ReC0** [comment]
> И очень важное замечания - @0ReC0 Не публикуй, пожалуйста, личную информацию сотрудников в публичных ресурсах. Как например тут - ФИО участников. В данной информации ничего секретного, по идее, нет, но если публиковать это - кто-то может по инерции и телефоны/почты/зарплаты случайно опубликовать, что не есть хорошо
> 
> Из того, как это можно реализовывать
> 
> 1. Можешь замазывать на готовом скриншоте
> 2. Можешь показывать на dev стенде, с рандомными но показывающими проблему данными
> 3. Можешь кинуть информацию в slack, и ответственный за проект уже создаст Issue

Заменил, спасибо

**Comment by 0ReC0** [comment]
> Взяв копию расчетного листа по твоему проекту, и округлив вверх все дробные значения до целых я получил увеличение стоимости проекта на 6% Учитывая, сколько времени вы тратите на общение, согласование, ожидание друг друга и прочее - количество реально неучтенного времени совершенно спокойно нивелирует эти колебания в получасовых (или где-то даже 0.2 часа видел) задачах Принцип, которого придерживаемся сейчас - часы это **целые** часы, если задача настолько маленькая, что на неё нужно пол часа - нужно объединить её с другой, более сложной, либо просто округлить до часа, ибо данная сумма не будет существенной в рамках всего проекта
> 
> Сегодня как раз будет собрание, сможем там этот вопрос обсудить

В моем случае да, это может быть не существенно. Если у меня много задач по 0.1, а они округляются до 1, то это уже не будет работать. Объединять? Зачем? Это отдельные задачи, которые могут вообще не пересекаться, и объединять их только для того, чтобы было "целое" значение, выглядит лишь как подстраивание под текущее положение дел, а не решение проблемы.

**Comment by Eloren1** [comment]
Если ты принципиально хочешь оплачивать в точности каждую десятую часа, то почему тогда не учитываешь время на согласование, обсуждение моментов, отчетность и, к примеру, съемку работы приложения? А ведь затраты на это не покроются даже при помощи округления времени.

**Comment by 0ReC0** [comment]
> Если ты принципиально хочешь оплачивать в точности каждую десятую часа, то почему тогда не учитываешь время на согласование, обсуждение моментов, отчетность и, к примеру, съемку работы приложения? А ведь затраты на это не покроются даже при помощи округления времени.

У меня нет идей как это покрывать, я просто это не учитываю в оплате, т.к. это и так покрывается высокой зарплатой  за час, могу быть не прав

**Comment by Eloren1** [comment]
Не прав, потому что при работе фуллтайм люди обсуждают задачи во время своего восьмичасового рабочего дня, что входит в их зарплату

**Comment by Suput** [comment]
@CAPCHIK @0ReC0 закрываем?

**Comment by 0ReC0** [comment]
> @CAPCHIK @0ReC0 закрываем?

Если не пишем дробные часы и немного врем, тогда видимо да.
