### ISSUE TITLE
Нет фильтрации на Фронте/Беке на версию проекта

### ISSUE THREAD

**Issue by 0ReC0** [RTUITLab/ITLab-Projects-Front#39]
# Bug
![image](https://user-images.githubusercontent.com/41593670/141866030-0662f03f-4407-425a-bc38-68b0e2448219.png)
## Я сначала заполнил информацию по версии 0.2.0, потом решил добавить информацию по версии 0.1.0. Теперь у меня отображается 1 версия вместо 2 как последняя. 
# Выставляйте пожалуйста информацию о проекте не по последней добавленной версии, а по строке версии проекта.

**Comment by 0B1t322** [comment]
Это вопрос скорее к беку, так как приходит это от меня
issue стоит направить в репозиторий бека

**Comment by Suput** [comment]
Закрываю - перенёс в [бэк](https://github.com/RTUITLab/ITLab-Projects/issues/51)
