### ISSUE TITLE
Возможность заверить неверный бюджет

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/ITLab-Projects-Front#40]
На данный момент в системе есть возможность заверить бюджет, не имеющий исполнителей. Это странно.
![image](https://user-images.githubusercontent.com/12235437/142005078-f0970554-a2e1-4af8-908c-3e0e309c53dc.png)

То же самое относится и к backend, который эту информацию сохраняет

При выполнении отметить галочку, @0B1t322 @FineBot 
- [x] Проверка на Backend
- [x] Проверка на Frontend

**Comment by 0B1t322** [comment]
Вся валидация - иметь задачи и хотя бы и одного исполнителя с часами?

**Comment by CAPCHIK** [comment]
Да, раобтник и задача - обязательное условие
