### ISSUE TITLE
Template instead of name 

### ISSUE THREAD

**Issue by baikinkirill** [RTUITLab/ITLab-Projects-Front#42]
![Screenshot_20211116-233316_VK.jpg](https://user-images.githubusercontent.com/10910903/142061375-12b653aa-2ea5-442a-8b74-e214d48e3696.jpg)

**Comment by Suput** [comment]
@baikinkirill пояснения пожалуйста

**Comment by baikinkirill** [comment]
@Suput, наша переписка ВК 16.11.2021 в 23:02

А так, там говорилось про пустые имена в ИТ Лабе

**Comment by CAPCHIK** [comment]
Суть про то, что Issue должен быть самодостаточным, для понимания желательно всеми участниками проекта, и стоит чуть подробнее описывать, что именно за задача тут обсуждается

**Comment by baikinkirill** [comment]
В itlab есть аккаунты с пустыми именами, которые сейчас отображаются как undefined undefined undefined, здесь про то, чтобы задать таким аккаунтам заготовленные имена

**Comment by Suput** [comment]
@baikinkirill этот вопрос уже решён?

**Comment by baikinkirill** [comment]
@Suput ещё нет

**Comment by baikinkirill** [comment]
Теперь да
