### ISSUE TITLE
Date format bug

### ISSUE THREAD

**Issue by baikinkirill** [RTUITLab/ITLab-Projects-Front#43]
![image.png](https://user-images.githubusercontent.com/10910903/142058873-1d9b4f48-1439-4f41-8fdd-a484bda7a3de.png)

**Comment by CAPCHIK** [comment]
Как полезный инстурмент для тестирования - 
https://www.browserstack.com/guide/test-websites-from-different-countries

**Comment by Suput** [comment]
@baikinkirill также при вводе этих самых дат, можно ввести что-то невнятное и оно подсветиться, что всё ок  
Предлагаю сделать какой-нибудь общий компонент с проверкой на регулярных выражениях:  
Сначала 2 числа (не меньше 01 и не больше 31. Тут же можно сделать зависимость от месяца)  
Потом обязательно точка, снова два числа для месяца (01 <= month <= 12), снова точка  
И в конце 4 цифры на год, начиная с 2006 (или когда там лаборатория основалась, я уже запамятовал)  
Почему 4 цифры на год? Потому что не думаю, что эта штука доживёт до 10000 года н. э.

**Comment by CAPCHIK** [comment]
Кажется, в соответствии с [этой статьей](https://www.w3.org/International/wiki/Locale-based_forms) и скриншотом текущего состояния – мы можем решить эту проблему довольно просто при помощи изменения lang в ITLab-Front-Root
![image](https://user-images.githubusercontent.com/12235437/152332236-c1de54d3-20f4-4855-8019-83e275e23903.png)
