### ISSUE TITLE
Incorrect tooltip shadow

### ISSUE THREAD

**Issue by baikinkirill** [RTUITLab/ITLab-Projects-Front#44]
![GDterUIhyPg.jpg](https://user-images.githubusercontent.com/10910903/142232220-81b01472-7c14-4c4b-895b-518a648bd3b9.jpg)

**Comment by Suput** [comment]
@baikinkirill продвижения?

**Comment by baikinkirill** [comment]
Не воспроизводится
Можешь у себя проверить?

![image](https://user-images.githubusercontent.com/10910903/152326765-deb99055-f7a9-4407-83f9-fc35a530c7dd.png)

**Comment by Suput** [comment]
@baikinkirill всё ок
