### ISSUE TITLE
Make overflow for tasks

### ISSUE THREAD

**Issue by Suput** [RTUITLab/ITLab-Projects-Front#47]
Одно из главных при просмотре версии - просмотр задач.  
Сейчас задачи даже с коротким названием не помещаются для просмотра и надо каждый раз наводить.  
Вижу два решения:
1. Переделать дизайн, чтобы дать больше места под таблицу  
2. Выделить под название задачи хотя бы 2-3 строчки

![image](https://user-images.githubusercontent.com/40500378/143431482-d75c2598-9dea-4971-936e-2460694668c6.png)

**Comment by CAPCHIK** [comment]
Для начала надо бы еще решить проблему с переполнением, ибо вот тут слово Обновлять неразумно занимает место, и текста должно быть больше. Я так понимаю, что переполнение считается по словам, но не вижу ничего плохого в том, чтобы съесть пару букв, но показать больше информации. На третьей строке, где всего два слова это заметно особенно

**Comment by Suput** [comment]
@baikinkirill продвижения?

**Comment by baikinkirill** [comment]
Если выделить под название 2-3 строчки, то нужно делать и остальные ячейки шире

**Comment by CAPCHIK** [comment]
Нет, выделить надо одну троку, но решить переполнение обычным css `text-overflow: ellipsis;`

Вот как сделано в Вике, и мне кажется, выше крыши, с учетом тултипа - отлично будет смотреться
![image](https://user-images.githubusercontent.com/12235437/152333300-32f4d380-1df3-4961-a44c-8d885c621eef.png)
![image](https://user-images.githubusercontent.com/12235437/152333310-2764522e-49b3-4339-b27b-99523bfe8468.png)

**Comment by baikinkirill** [comment]
Я бы вот так оставил

![image](https://user-images.githubusercontent.com/10910903/152334400-9254b2e9-deec-46f1-a026-4882c1b4e487.png)

**Comment by CAPCHIK** [comment]
Если галка слева "прибита" в левому краю ячейки, а не левому краю текста - да, вполне себе

В плане чтобы все галки были друг под другом, это не к этому Issue, да, просто как мысль

**Comment by Suput** [comment]
Мне нравится. Закрываем?

**Comment by CAPCHIK** [comment]
Как только окажется на проде
