### ISSUE TITLE
Incorrect color on version creating

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/ITLab-Projects-Front#48]
В темной теме текст тоже черный, что не сказать что очень удобно

Надо проверить, что в других полях для ввода ситуация не повторяется

- [ ] @Suput проверить все markdown редакторы
- [ ] @FineBot исправить поведение

![image](https://user-images.githubusercontent.com/12235437/143820502-579e2cfc-52b1-4508-8e41-4994b0530f0d.png)

**Comment by Suput** [comment]
@FineBot пример (внимание на заголовки)
![image](https://user-images.githubusercontent.com/40500378/150324604-3f3df6b3-8237-4217-aa77-88fa965f8caa.png)
