### ISSUE TITLE
Create README.md

### ISSUE THREAD

**Issue by Suput** [RTUITLab/ITLab-Projects-Front#52]
Описать:
1. Сборку (какие команды, какие переменные нужно указать)
2. Как запустить

**Comment by CAPCHIK** [comment]
Для dev режима можно/нужно прописать в ридми параметры, которые будут завязаны на localhost, это теперь к @Suput 

Так и для прода будет ясно виден формат

**Comment by Suput** [comment]
@CAPCHIK я сделаль
@baikinkirill тоже проверь на всякий

**Comment by CAPCHIK** [comment]
Тогда @baikinkirill  как проверишь - закрывай Issue

**Comment by Suput** [comment]
И слей изменения мои в мастер
