### ISSUE TITLE
Incorrect dropdown color 

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/ITLab-Projects-Front#56]
В светлой теме на мастере дропдаун имеет неверный цвет, в темной все ок

![image](https://user-images.githubusercontent.com/12235437/152155834-e57c8ebb-b4af-4a76-92f9-22c081fa4e9d.png)
![image](https://user-images.githubusercontent.com/12235437/152155839-90c1bef3-07af-4774-9004-4783511a998f.png)

**Comment by baikinkirill** [comment]
Но он же по дизайну одинаковый на обеих темах
![Screenshot_20220202-165452_Opera.jpg](https://user-images.githubusercontent.com/10910903/152167326-64d3a0fe-151b-4b0d-b88e-28007adc86b8.jpg)

**Comment by CAPCHIK** [comment]
@Suput я что-то вообще не уверен, что это нормально, Свету придется дернуть тебе лично, ибо тегать её тут смысла мало

**Comment by Suput** [comment]
@baikinkirill @CAPCHIK Света предложила следующий вариант:
Сделать две отдельные кнопки "*значок фильтра* по названию" и "*значок фильтра* по дате"
Текущий фильтра обводить синим. Сюда же можно сделать "повторное нажатие переворачивает сортировку" и менять *значок фильтра* на перевернутый

**Comment by baikinkirill** [comment]
> @baikinkirill @CAPCHIK Света предложила следующий вариант:
> Сделать две отдельные кнопки "*значок фильтра* по названию" и "*значок фильтра* по дате"
> Текущий фильтра обводить синим. Сюда же можно сделать "повторное нажатие переворачивает сортировку" и менять *значок фильтра* на перевернутый
> 

Звучит удобно)

**Comment by Suput** [comment]
@CAPCHIK опять же - фиксить это сейчас или оставить на редизайн?

**Comment by CAPCHIK** [comment]
На редизайн
