### ISSUE TITLE
При поиске не учитывать спец символы и пробелы

### ISSUE THREAD

**Issue by Suput** [RTUITLab/ITLab-Projects-Front#57]
- [x] При поиске по отображаемым проектам не учитывать спец символы и пробелы. Как пример: найти VR-Duel по символам 'vrd'
![image](https://user-images.githubusercontent.com/40500378/152322699-bd7b7a3c-6697-4616-9d72-8762bccc3314.png)
- [x] При ненахождении проектов показывать, что по такому запросу ничего не найдено
![image](https://user-images.githubusercontent.com/40500378/152322709-9e40ba55-54f2-4685-91b1-a2c80fb88232.png)

**Comment by baikinkirill** [comment]
![image](https://user-images.githubusercontent.com/10910903/154733142-64bd46ec-60eb-4b9a-a993-7d98217fafe6.png)

хм

**Comment by Suput** [comment]
@baikinkirill 
Что такое?

**Comment by baikinkirill** [comment]
Он вроде нашел и проигнорировал - и ;

**Comment by Suput** [comment]
Добавил проект `VR-Duel` на дев сервер. Поиск через `vrd` не работает

**Comment by baikinkirill** [comment]
А точно ли это к фронту?)

**Comment by Suput** [comment]
> При ненахождении проектов показывать, что по такому запросу ничего не найдено

Этот пункт точно выполнен?
![image](https://user-images.githubusercontent.com/40500378/155126696-25586804-dbbe-488e-97af-65fe5f19bc69.png)

Как вообще работает поиск?
@0B1t322 подскажешь?
![image](https://user-images.githubusercontent.com/40500378/155126673-63bc679c-2375-4831-9eba-db05c052ad09.png)

**Comment by 0B1t322** [comment]
> > При ненахождении проектов показывать, что по такому запросу ничего не найдено
> 
> Этот пункт точно выполнен? ![image](https://user-images.githubusercontent.com/40500378/155126696-25586804-dbbe-488e-97af-65fe5f19bc69.png)
> 
> Как вообще работает поиск? @0B1t322 подскажешь? ![image](https://user-images.githubusercontent.com/40500378/155126673-63bc679c-2375-4831-9eba-db05c052ad09.png)

Поиск это просто отправка match запроса по вхождению символов

**Comment by baikinkirill** [comment]
Пункт с отображением, если не нашел проекты, сейчас не на деве
