### ISSUE TITLE
Delete production variables

### ISSUE THREAD

**Issue by IvLaptev** [RTUITLab/ITLab-Projects-Front#58]
В корне проекта лежит `.env.production`. Не совсем понимаю, откуда он взялся, но надо, чтобы он пропал.

Параллельно надо, чтобы @Suput проверил, что без данного файла фронт нормально развернётся.

**Comment by Suput** [comment]
@baikinkirill 
Судя по [первой](https://github.com/RTUITLab/ITLab-Projects-Front/blob/6dca83ad753dd88d9252a0200a05d051ccabdb3a/src/api.js#L1) и [второй](https://github.com/RTUITLab/ITLab-Projects-Front/blob/6dca83ad753dd88d9252a0200a05d051ccabdb3a/src/api.js#L2) строчкам без переменных `REACT_APP_API_URL` и `REACT_APP_API_HOST` оно собраться и прожить сможет
Меня интересует [эта](https://github.com/RTUITLab/ITLab-Projects-Front/blob/6dca83ad753dd88d9252a0200a05d051ccabdb3a/src/api.js#L28) строчка. Если не указать переменную там будет `undefined` и оно заработает? Окей если да
@IvLaptev @CAPCHIK [так](https://github.com/RTUITLab/ITLab-Projects-Front/blob/6dca83ad753dd88d9252a0200a05d051ccabdb3a/src/App.js#L102) и [так](https://github.com/RTUITLab/ITLab-Projects-Front/blob/6dca83ad753dd88d9252a0200a05d051ccabdb3a/src/components/popouts/addFuncTask.js#L26) делать нормально?

**Comment by baikinkirill** [comment]
Я как приеду домой - сделаю, чтобы можно было удалить этот файл

**Comment by CAPCHIK** [comment]
Нет, принято не хардкодить урлы в коде в любом случае
